version: "3.8"
services:

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://app:4000
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Map container port 4000 to host port 4000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Map Redis default port
    command: ["redis-server", "--appendonly", "yes"] # Persist data to disk
    volumes:
      - redis_data:/data

volumes:
  redis_data:
