version: "3.9" # Specify the Docker Compose version

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000" # Map backend port 4000 to host
    depends_on:
      - redis # Ensure Redis starts before the backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173" # Map frontend port 5173 to host
    depends_on:
      - backend # Ensure backend starts before frontend
    networks:
      - app-network

  redis:
    image: redis:6.2 # Use the official Redis image
    container_name: redis
    ports:
      - "6379:6379" # Map Redis port 6379 to host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
